In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import NearestNeighbors

In [10]:
df = pd.read_csv('/Users/Koh/Documents/2017-_SNU/Research/DM/data/ML/Bestseller_Children.csv', encoding="cp949")

In [11]:
df

BestsellerChildren            Genre  GenreBin  \
0                 2020  Children'sBooks         3   
1                 2020  Children'sBooks         3   
2                 2020  Children'sBooks         3   
3                 2020  Children'sBooks         3   
4                 2020  Children'sBooks         3   
..                 ...              ...       ...   
91                2012  Children'sBooks         3   
92                2012  Children'sBooks         3   
93                2011  Children'sBooks         3   
94                2011  Children'sBooks         3   
95                2011  Children'sBooks         3   

                                             Title  \
0   School Zone - Big Preschool Workbook - Ages 4…   
1                     If Animals Kissed Good Night   
2                      The Very Hungry Caterpillar   
3                             Giraffes Can't Dance   
4           Brown Bear Brown Bear What Do You See?   
..                                             ...   
91            LEGO NINJAGO: Character Encyclopedia   
92       Cabin Fever (Diary of a Wimpy Kid Book 6)   
93                               Every Thing On It   
94                     Guinness World Records 2012   
95                    The Invention of Hugo Cabret   

                            Author  Published Year                  Publisher  \
0                      School Zone            2018     School Zone Publishing   
1                Ann Whitford Paul            2014  Farrar Straus and Giroux    
2                       Eric Carle            1981       World of Eric Carle    
3                    Giles Andreae            2012            Cartwheel Books   
4   Bill Martin Jr. and Eric Carle            2020   Henry Holt and Co. (BYR)   
..                             ...             ...                        ...   
91                              DK            2016                DK Children   
92                     Jeff Kinney            2011            Harry N. Abrams   
93                Shel Silverstein            2011              HarperCollins   
94          Guinness World Records            2011    Guinness World Records    
95                  Brian Selznick            2007           Scholastic Press   

    Page  Price  authorgender(male0fe1team2)  isFirstBestSeller Duration  \
0    320  12.99                            2                  1        3   
1     34   7.99                            1                  1        4   
2     32  21.99                            0                  0        8   
3     32  16.99                            0                  1        7   
4     24   8.99                            0                  0        6   
..   ...    ...                          ...                ...      ...   
91   224  18.99                            2                  1        1   
92   224  14.99                            0                  0        2   
93   208   7.30                            0                  1        1   
94   288  28.95                            2                  1        1   
95   533  24.99                            0                  1        1   

    변경전Duration  변경후Duration3(0=S1=L2=etc)        Impact year_rank  \
0             1                          1  1.397000e+08   2019_09   
1             1                          1  1.562000e+04   2019_24   
2             1                          1  1.386000e+05   2019_16   
3             1                          1  5.403860e+03   2019_23   
4             1                          1  7.037929e+03   2019_48   
..          ...                        ...           ...       ...   
91            0                          0  6.988100e+07       NaN   
92            0                          1  6.000000e+04       NaN   
93            0                          0  1.700000e+04       NaN   
94            0                          0  2.090000e+05       NaN   
95            0                          0  1.344030e+04      

In [12]:
df_x = df[['Published Year', 'Page', 'Price','authorgender(male0fe1team2)', 'isFirstBestSeller','Impact', 'isGlobal50 of first year(False=0True=1)']]
df_y = df['변경후Duration3(0=S1=L2=etc)']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state = 100)

In [14]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train[:] = np.nan_to_num(x_train)
y_train[:] = np.nan_to_num(y_train)


In [15]:
cov = np.cov(x_train, rowvar=False)
kNN = KNeighborsClassifier(algorithm='brute', n_neighbors = 9, metric = 'mahalanobis', metric_params=dict(V=cov))

In [16]:
kNN.fit(x_train, y_train)

KNeighborsClassifier(algorithm='brute', metric='mahalanobis',
                     metric_params={'V': array([[ 1.01333333e+00,  2.99227859e-01, -5.74415646e-02,
         9.83122047e-03, -1.22884249e-01,  3.62235356e-02,
        -1.12288173e-01],
       [ 2.99227859e-01,  1.01333333e+00,  2.48666286e-01,
        -2.36185138e-01, -2.90624947e-01, -5.71642114e-02,
        -2.84354698e-01],
       [-5.74415646e-02,  2.48666286e-01,  1.01333333e...
         1.00841668e-03],
       [-1.22884249e-01, -2.90624947e-01, -1.13601198e-01,
         3.96690872e-01,  1.01333333e+00, -5.62316371e-04,
        -9.18022614e-02],
       [ 3.62235356e-02, -5.71642114e-02, -1.19251035e-01,
         4.94424240e-01, -5.62316371e-04,  1.01333333e+00,
         4.17169936e-02],
       [-1.12288173e-01, -2.84354698e-01,  2.42787150e-01,
         1.00841668e-03, -9.18022614e-02,  4.17169936e-02,
         1.01333333e+00]])},
                     n_neighbors=9)

In [17]:
print(kNN.score(x_train, y_train))

0.7368421052631579


In [18]:
print(kNN.score(x_test, y_test))

0.65


/Users/Koh/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py:1456: FutureWarning: from version 0.25, pairwise_distances for metric='mahalanobis' will require VI to be specified if Y is passed.
  warnings.warn("from version 0.25, pairwise_distances for "


In [19]:
y_pred = kNN.predict(x_test)

/Users/Koh/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py:1456: FutureWarning: from version 0.25, pairwise_distances for metric='mahalanobis' will require VI to be specified if Y is passed.
  warnings.warn("from version 0.25, pairwise_distances for "


In [20]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
confusion_matrix(y_test, y_pred, labels = [1, 0])

array([[ 3,  5],
       [ 2, 10]])

In [22]:
conf_matrix = pd.DataFrame(confusion_matrix(y_test, y_pred), columns=['pred_0', 'pred_1'], index=['true_0', 'true_1'])

In [23]:
conf_matrix

pred_0  pred_1
true_0      10       2
true_1       5       3

In [24]:
from sklearn.metrics import roc_curve, auc
from matplotlib import pyplot as plt

In [25]:
kNN.predict_proba(x_valid)

NameError: name 'x_valid' is not defined

In [26]:
fpr, tpr, _ = roc_curve(y_test, kNN.predict_proba(x_valid)[:,1])

# Calculate the AUC
roc_auc = auc(fpr, tpr)
print('ROC AUC: %0.3f' % roc_auc)

# Plot of a ROC curve for a specific class
plt.figure()
plt.plot(fpr, tpr, color='darkorange', label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

NameError: name 'x_valid' is not defined

In [730]:
fpr

array([0.        , 0.08333333, 0.16666667, 0.41666667, 0.83333333,
       1.        ])

In [731]:
tpr

array([0.  , 0.25, 0.75, 1.  , 1.  , 1.  ])

In [732]:
predictions = kNN.predict(x_valid)

C:\Anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:1456: FutureWarning: from version 0.25, pairwise_distances for metric='mahalanobis' will require VI to be specified if Y is passed.
  warnings.warn("from version 0.25, pairwise_distances for "


In [733]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [734]:
print(f'Accuracy: {accuracy_score(y_valid, predictions):0.3f}')
print(f'Precision: {precision_score(y_valid, predictions):0.3f}')
print(f'Recall: {recall_score(y_valid, predictions):0.3f}')
print(f'f1: {f1_score(y_valid, predictions):0.3f}')

Accuracy: 0.800
Precision: 0.750
Recall: 0.750
f1: 0.750


In [735]:
Accuracy: 0.400
Precision: 0.333
Recall: 0.500
f1: 0.400